[server]
enableStaticServing = true

[[theme.fontFaces]]
family="Inter"
url="app/static/Inter_18pt-Regular.ttf"
style="normal"

[theme]
font="Inter"
base = "light"
primaryColor="#ADD8E6"
textColor="#000000"
